packages:
  - 'packages/*'
  - 'web'
catalog:
  "@tsconfig/node22": 22.0.2
  "@types/aws-lambda": 8.10.155
  "@types/react": 19.2.2
  "@types/react-dom": 19.2.1
  "react": 19.2.0
  "react-dom": 19.2.0
  "sst": 4.3.6
  "typescript": 5.9.3
  "zod": 4.1.12
